config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/gallery'
  get 'static_pages/treatments'
  get 'static_pages/foot_health'
  get 'static_pages/classes'
  get 'static_pages/shop'
  get 'static_pages/reviews'

  devise_for :users
  resources :welcomes

  root 'welcomes#index'
  get '/galleries' => 'galleries#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 private
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'static_application'
  def about
    @bio = ""
  end
  def privacy_policy
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]
  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all.order(:role)
    @main_welcome = Welcome.where(role: 'main')
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def landing
    render layout: "landing_layout"
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.require(:welcome).permit(:title, :notes, :headline, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper

  def get_tags
    client = Instagram.client(:access_token => session[:access_token])
    html = "<div class='row'><p class='transparent-light text-center'>Add a photo to your instagram with #nashvilleOM and see it here!</p></div></div></div>"
    tags = client.tag_search('nashvilleOM')

    client.inspect
    for media_item in client.tag_recent_media(tags[0].name, count:50)
      html << "<div class='col-sm-4 col-xs-6'><a href='#{media_item.link}'><img class='col-xs-12 img img-responsive' src='#{media_item.images.standard_resolution.url}'></a><a class='hidden-xs' href='https://www.instagram.com/#{media_item.user.username}' target='none'><div class='transparent-dark text-center'> photo by: " + media_item.user.username + "</div></a></div>"
    end
    html << "<div class='lg-spacer'></div>"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/galleries/index.html.erb
<div class='row'>
  <h1 class='transparent-light text-center'>Gallery</h1>
</div>
<div class='row transparent-dark'>
  <div class='col-md-6'>
    <%= image_tag('Lew', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
  <div class='col-md-6'>
    <%= image_tag('fam', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
  <div class='col-md-6'>
    <%= image_tag('dojo', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
</div>
<div class='row transparent-dark'>
  <div class='col-md-6'>
    <%= image_tag('correct-toes', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
  <div class='col-md-6'>
    <%= image_tag('spreadtoes', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
</div>
<div class='row transparent-dark'>
  <div class='col-md-6'>
    <%= image_tag('SuperFicial-Back', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
  <div class='col-md-6'>
    <%= image_tag('back', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
  <div class='col-md-6'>
    <%= image_tag('chain', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
  <div class='col-md-6'>
    <%= image_tag('natchez', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
</div>
<div class='row transparent-dark'>

  <div class='col-md-6'>
    <%= image_tag('hanger', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
</div>
<div class='row transparent-dark'>
  <div class='col-md-6'>
    <%= image_tag('sound', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
  <div class='col-md-6'>
    <%= image_tag('spiral', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
</div>
<div class='row transparent-dark'>
  <div class='col-md-6'>
    <%= image_tag('circlepurple', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
  <div class='col-md-6'>
    <%= image_tag('spiraltones', id: 'index-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
  </div>
</div>
<div class='xs-spacer'></div>


<div class='xs-spacer'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "NashvilleOrthopedicMassage" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-180x180-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

  </head>
  <body id='application-layout'>
    <%= render 'shared/navbar'%>
    <div class="container-fluid">
      <div class="row">
        <%= render 'shared/header'%>
          <%= bootstrap_flash %>
          <%= yield %>
          <div class='transparent-light'>
            <footer class='col-md-12'>
              <h3 class='text-center'>
                <%= t(:address_html) %>
              </h3>
            </footer>
          </div>
        </div>
      </div>
    <div class='xs-spacer'></div>
  </body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-71572758-1', 'auto');
    ga('send', 'pageview');
  </script>
</html>

app/views/layouts/landing_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "NashvilleOrthopedicMassage" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body id='layout'>
    <div class="container">
      <div class="row">
        <div class="col-md-offset-1 col-md-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
        <p>&copy; <%= t(:client) %> Nashville 2015 - 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-71572758-1', 'auto');
    ga('send', 'pageview');
  </script>
</html>

app/views/layouts/static_application.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title>
      <%= content_for?(:title) ? yield(:title) : "NashvilleOrthopedicMassage" %>
    </title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png',
        :rel => 'apple-touch-icon-precomposed', :type => 'image/png',
        :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png',
        :rel => 'apple-touch-icon-precomposed', :type => 'image/png',
        :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png',
        :rel => 'apple-touch-icon-precomposed', :type => 'image/png',
        :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png',
        :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

  </head>

  <body id='static-pages-application-layout'>
    <%= render 'shared/navbar'%>
    <div class="container-fluid">
      <div class="row">
        <%= render 'shared/header'%>
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->
    </div><!--/container-->
    <div class='xs-spacer'></div>
    <div class='container'>
      <div class='transparent-light'>
        <footer class='col-md-12'>
          <h3 class='text-center'>
            <%= t(:client) %><br>
            <%= t(:address_html) %>
          </h3>
        </footer>
      </div>
    </div> <!-- /container -->
  </body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-71572758-1', 'auto');
    ga('send', 'pageview');
  </script>

</html>

app/views/shared/_header.erb
<div class="heading hidden-xs">
  <figure class='square-logo figure fixed hidden-xs'>
    <%= image_tag 'horizontal-logo.png', class: 'figure-img img-fluid img-rounded', alt:"Nashville Orthopedic Massage's logo featuring DaVinci's 'Vitruvian Man'"%>
  </figure>
  <span class='nom text-bottom col-md-4 hidden-xs'>NASHVILLE ORTHOPEDIC MASSAGE</span>
</div>
<h3 class='hidden-sm hidden-md hidden-lg hidden-xl remove-margin'>
  <figure class='horizontal-logo figure '>
    <%= image_tag 'horizontal-logo.png', class: 'hidden-sm col-xs-12 figure-img img-fluid img-rounded', alt:"Nashville Orthopedic Massage's logo featuring DaVinci's 'Vitruvian Man'"%>
  </figure></h3>
  <div class="tagline text-center hidden-sm hidden-md hidden-lg hidden-xl">
      Finding Health by <strong>defining balance</strong> ...
  </div>

app/views/shared/_hours.erb
  <h4 class='hours transparent-light text-center'>
    <label>Hours:</label>
    Monday - Friday - 9am - 6pm
  </h4>

app/views/shared/_nav_buttons.erb
<ul class="nav navbar-nav navbar-collapse">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "About", static_pages_about_path %></li>
  <li><%= link_to "Contact", static_pages_contact_path %></li>
  <li><%= link_to "Foot Health", static_pages_foot_health_path %></li>
  <li><%= link_to "Treatments", static_pages_treatments_path %></li>
  <!-- <li><%= link_to "Shop", galleries_path %></li> -->
  <!-- <li><%= link_to "Classes & Education", galleries_path %></li> -->
</ul>

app/views/shared/_navbar.erb
<%= render 'shared/social_buttons'%>
<nav class="navbar navbar-default pull-right col-xs-12 col-sm-7 col-md-8 col-lg-8">
  <span class='navbar-brand hidden-sm hidden-md hidden-lg'>Nashville Orthopedic Massage</span>
  <!-- Brand and toggle get grouped for better mobile display -->

  <div class="navbar-header">

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse collapse navbar-responsive-collapse text-right pull-right">
      <%= render 'shared/nav_buttons'%>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/shared/_privacy_policy.erb
<h4 class='transparent-light pull-right hours'>
  <label>Privacy Policy:</label><br>
  <p>
    Our gallery will display recent Instagram images labeled with #nashvilleOM.
    Images are never saved or used again.  The purpose is making our website's gallery a community
    experience recording good times at our venue/bar.  It offers immediate gratification for the user/customer
    when they get to see their picture on our website.
  </p><br>
</h4>

app/views/shared/_social_buttons.erb
<div class='share fixed transparent-light'>
  <div class="text-right">
    <a href="https://www.massagebook.com/biz/NashvilleOrthopedicMassage#services"
       target='_blank'>
       <img src="http://www.massagebook.com/home/img/getbutton/button-booknow.png" alt="Book Now on MassageBook.com!" border="0">
     </a>
        <%= link_to (glyph :phone ) + '615-310-5359', 'tel:+1+615-310-5359', class:'btn btn-link btn-lg hidden-xs' %>
        <%= link_to (glyph :phone ), 'tel:+1+615-310-5359', class:'btn btn-default btn-lg hidden-sm hidden-md hidden-lg' %>
        <div class="fb-like"
             data-href="https://www.facebook.com/HarmonicHealthAndBodyworkNashville/"
             data-layout="button" data-action="like" data-share="true">
        </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1 class='col-xs-12 col-sm-12 col-md-12 transparent-light text-center'><%= t(:about) %></h1>
<div class='transparent-dark'>
  <div class='transparent-light col-sm-12'>
    <figure class='col-sm-4 col-md-4 col-lg-4 hidden-xs'>
      <%= image_tag 'Lew', class:'img img-responsive' %><caption>Lewis</caption>
    </figure>
    <%= t(:lew) %>
    <p>
      <%= t(:about_lew) %>
      <br>
      <br>
      In 2003, I began studying massage and working as resource coordinator, office administrator, and continuing education coordinator at the Natural Health Institute.
      <br>
      <br>
      Upon graduation and licensure in 2005, I started a bodywork practice in the NHI clinic and in 2007 became an instructor. I created the Sound Body Integration© class to share the healing power of sound with others. Currently in my tenth year of practice, I continue to provide education, awareness and integral holistic therapy.
      <br>
      <br>
        I live with my wife and <strike>four</strike> five beautiful children in the rolling hills of Bellevue where we enjoy nature, music, art, play time, gardening, and meals with friends and family.
      <br>
      <caption>The Braswells</caption>
      <%= image_tag 'fam', class:'img img-responsive' %>
    </p>
  </div>
</div>
<div class='transparent-dark'>
  <div class='transparent-light col-sm-12'>
    <%= t(:camo) %>
    <p>
      <%= t(:about_camo_html) %>
    </p>
  </div>
</div>

app/views/static_pages/classes_and_education.html.erb
<h1 class='col-xs-12 col-sm-12 col-md-12 transparent-light text-center'>Classes and Education</h1>
<div class='transparent-dark'>
  <div class='col-md-offset-1'>
    <%= render 'shared/hours' %>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class='container'>
  <h1 class='col-xs-12 col-sm-12 col-md-12 transparent-light text-center'>Contact</h1>
  <div class='transparent-dark'>
    <div class='col-sm-12'>
      <div class='col-sm-6'>
        Monday - Friday - 9am - 6pm
        <address>
          <%= t(:client) %><br>
          <%= t(:address_html) %><br>
          <%= link_to 'MassageBook', 'https://www.massagebook.com/Nashville~Massage~NashvilleOrthopedicMassage', class:'btn-link', target: 'blank' %><br>
        </address>
      </div>
      <div class='col-sm-6'>
        <%= t(:lew) %>
        <br>
        <%= link_to t(:email),
        'mailto:lew@nashvilleom.com?subject=Nashville Orthopedic Massage.&body=
         I would like to book a session!', class:'btn-link'%><br>
        <%= link_to '615-310-5359', 'tel:+1+615-310-5359', class:'btn-link' %><br>
        <br>
        <%= t(:camo ) %>
        <br>
        <%= link_to 'cameron@nashvilleom.com',
        'mailto:cameron@nashvilleom.com?subject=Nashville Orthopedic Massage.&body=
         I would like to book a session!', class:'btn-link'%><br>
         <%= link_to '615-485-1920', 'tel:+1+615-485-1920', class:'btn-link' %><br>
      </div>
      <h2 class='transparent-light text-center'>Map</h2>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3221.582968037486!2d-86.84864418432588!3d36.15236611159554!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8864616bed9d741f%3A0x6d0ec6c1f9b0e5b8!2sNashville+Orthopedic+Massage!5e0!3m2!1sen!2sus!4v1496259239353" width="800" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/static_pages/privacy-policy.html.erb
<%= render 'shared/privacy_policy' %>

app/views/static_pages/shop.html.erb
<h1 class='transparent-light text-center'>Shop</h1>
<div class='transparent-dark'>
  <div class='col-md-offset-1'>
    <%= render 'shared/hours' %>
  </div>
</div>

app/views/welcomes/edit.html.erb
<%- model_class = Welcome -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/welcomes/landing.html.erb
<div>
  <%= link_to 'Enter', welcomes_path, class:'btn btn-default col-md-12', id: 'click'%>
  <%= image_tag('night-owl-logo', id: 'landing-logo', class: 'img img-responsive animated slideInUp col-md-12') %>
</div>
<h1 class='text-center'>Click the owl and have a hoot!
</h1>
<div class='col-md-offset-6 checkbox pull-left'>
  <%= glyph 'volume-off' %>
</div>
<div class='checkbox pull-left'>
  <label>
    <%= check_box_tag 'Mute', id: 'mute', class:'checkbox' %>
  </label>
</div>
<%= audio_tag 'horned_owl.wav', id: 'owl-hoot' %>

app/views/welcomes/new.html.erb
<%- model_class = Welcome -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>